# Generated by Django 5.1.6 on 2025-02-28 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Era',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('is_custom', models.BooleanField(default=False, verbose_name='用户自定义')),
            ],
            options={
                'verbose_name': '时代背景',
                'verbose_name_plural': '时代背景',
            },
        ),
        migrations.CreateModel(
            name='NarrativePerspective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('is_custom', models.BooleanField(default=False, verbose_name='用户自定义')),
            ],
            options={
                'verbose_name': '叙事视角',
                'verbose_name_plural': '叙事视角',
            },
        ),
        migrations.CreateModel(
            name='NarrativeStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('is_custom', models.BooleanField(default=False, verbose_name='用户自定义')),
            ],
            options={
                'verbose_name': '叙事风格',
                'verbose_name_plural': '叙事风格',
            },
        ),
        migrations.CreateModel(
            name='NovelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('is_custom', models.BooleanField(default=False, verbose_name='用户自定义')),
            ],
            options={
                'verbose_name': '小说类型',
                'verbose_name_plural': '小说类型',
            },
        ),
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('location', models.TextField(blank=True, null=True, verbose_name='地点设定')),
                ('social_structure', models.TextField(blank=True, null=True, verbose_name='社会结构')),
                ('cultural_traits', models.TextField(blank=True, null=True, verbose_name='文化特征')),
                ('details', models.JSONField(default=dict, verbose_name='详细信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('published', models.BooleanField(default=False, verbose_name='已发布')),
                ('era', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='novel.era', verbose_name='时代')),
                ('style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='novel.narrativestyle', verbose_name='风格')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('viewpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='novel.narrativeperspective', verbose_name='视角')),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='novel.noveltype', verbose_name='类型')),
            ],
            options={
                'verbose_name': '小说',
                'verbose_name_plural': '小说',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='章节序号')),
                ('title', models.CharField(blank=True, default='', max_length=100, verbose_name='章节标题')),
                ('summary', models.TextField(blank=True, default='', verbose_name='章节概要')),
                ('characters_change', models.TextField(blank=True, default='', verbose_name='人物变化')),
                ('conflict', models.TextField(blank=True, default='', verbose_name='矛盾冲突')),
                ('mood', models.CharField(blank=True, default='', max_length=50, verbose_name='氛围基调')),
                ('keywords', models.CharField(blank=True, default='', max_length=200, verbose_name='关键词')),
                ('content', models.TextField(blank=True, verbose_name='章节内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='novel.novel', verbose_name='所属小说')),
            ],
            options={
                'verbose_name': '章节',
                'verbose_name_plural': '章节',
                'ordering': ['order'],
                'unique_together': {('novel', 'order')},
            },
        ),
    ]
