# Generated by Django 5.1.6 on 2025-03-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("novel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="published",
            field=models.BooleanField(default=False, verbose_name="已发布"),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="完成时间"),
        ),
    ]
