# Generated by Django 5.1.6 on 2025-03-02 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("novel", "0002_chapter_published_alter_chapter_created_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chapter",
            options={
                "ordering": ["order", "created_at"],
                "verbose_name": "章节",
                "verbose_name_plural": "章节",
            },
        ),
        migrations.AlterUniqueTogether(
            name="chapter",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="章节顺序"),
        ),
        migrations.CreateModel(
            name="NovelReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(blank=True, default="", verbose_name="评论内容"),
                ),
                (
                    "rating",
                    models.PositiveIntegerField(default=5, verbose_name="评分(1-5)"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="评论时间"),
                ),
                (
                    "novel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="novel.novel",
                        verbose_name="所属小说",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="评论用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "小说评论",
                "verbose_name_plural": "小说评论",
                "unique_together": {("novel", "user")},
            },
        ),
    ]
